# Generated by Django 3.1.4 on 2024-08-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20240827_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
